language: python

# requires for python 3.7 currently
sudo: required
dist: xenial

python:
- '3.7'

services:
  - redis  # 对应 redis-server 启动命令 `sudo systemctl start redis-server`

before_install:
- openssl aes-256-cbc -K $encrypted_e4e604bd9825_key -iv $encrypted_e4e604bd9825_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xv -f secrets.tar -C ~ # 解打包

install:
- pip install --upgrade pip
- pip install pipenv
- pipenv sync --dev

script:
- pytest --cov=./
- codecov --token=$CODECOV_TOKEN

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    tags: true
#    branch: master  # tags 为 true 的情况下，这个条件会被忽略掉
