{
  "SECRET_KEY": "gfdhfghnbvn",
  "DEBUG": false,
  "TESTING": false,
  "ELASTICSEARCH_URL": "",
  "SQLALCHEMY_DATABASE_URI": "sqlite:///:memory:",
  "SQLALCHEMY_TRACK_MODIFICATIONS": true,
  "IS_AUTH_ENABLED": false,
  "IS_ERROR_MAIL_ENABLED": false,
  "LOG_LEVEL": 10,
  "ADMINS": ["xiaoyin_c@qq.com"],
  "BOT_TOKEN": "test_token",
  "VERIFICATION_CODE_EXPIRES": 180,
  "TURING_API": "http://openapi.tuling123.com/openapi/api/v2",
  "TURING_KEY": "",
  "SHORT_URL_API": "http://xhup.club/index.php/Home/Service/getShortUrl",
  "SHORT_URL_TOKEN": "",
  "REDIS0_URL": "redis://localhost:6379/0",
  "RQ_REDIS_URL": "redis://localhost:6379/1",
  "CAPTCHA_FORMAT": "captcha:{}",
  "GROUP_BIND_VERI_FORMAT": "group_user_relation:{}",
  "RESET_PASSWORD_VERI_FORMAT": "reset_password:{}",
}