# api 接口的功能测试

## 线上服务器
@hostname = xhup.club
@port = 8000

## 本地测试服务器
# @hostname = localhost
# @port = 8000

@host = {{hostname}}:{{port}}

### 注册测试
POST http://{{host}}/api/v1/user/ HTTP/1.1
Content-Type: application/json

{
    "username": "ryan",
    "email": "ryan@example.com",
    "password": "ihaveadream"
}


### 永久删除用户
# 已知 bug：绑定平台账号后（比如绑定 qq群），删除账号会报 500 错误

DELETE http://{{host}}/api/v1/user/ HTTP/1.1
Content-Type: application/json

{
    "password": "ihaveadream"
}


### 登录测试

POST http://{{host}}/api/v1/session/ HTTP/1.1
Content-Type: application/json

{
    "username": "ryan",
    "password": "ihaveadream",
    "remember_me": false
}

### 登出测试

DELETE http://{{host}}/api/v1/session/ HTTP/1.1


### 拆字表上传测试
#  仅绑定 QQ 群管理员账号的用户，可使用此 api，暂时无法线上测试
POST http://{{host}}/api/v1/characters/table/ HTTP/1.1
Content-Type: application/json

{
    "version": "0.0.1",
    "table_name": "小鹤音形拆字表",
    "table_type": "xhup",
    "table": "比：　bi bibb*=拆分：　比左 匕=首末：　比左 匕=编码：　b  b\n顷：　qkb qkbr=拆分：　比左 一 ノ 冂 人=首末：　比左 人=编码：　b  r\n皆：　jpb jpbb=拆分：　比左 匕 白=首末：　比左 白=编码：　b  b",
    "group_id": "12354321",
    "platform": "qq"
}


### 拆字查询
GET http://{{host}}/api/v1/characters/info/ HTTP/1.1
Content-Type: application/json

{
    "version": "0.0.1",
    "table_name": "小鹤音形拆字表",
    "char": "顷"
}
