"""empty message

Revision ID: 0253176ac39b
Revises: 75c03fa5228c
Create Date: 2019-03-06 20:59:18.574638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0253176ac39b'
down_revision = '75c03fa5228c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chars_table', sa.Column('group_db_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chars_table_group_db_id'), 'chars_table', ['group_db_id'], unique=False)
    op.drop_index('ix_chars_table_group_id', table_name='chars_table')
    op.drop_constraint('chars_table_group_id_fkey', 'chars_table', type_='foreignkey')
    op.create_foreign_key(None, 'chars_table', 'group', ['group_db_id'], ['id'])
    op.drop_column('chars_table', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chars_table', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chars_table', type_='foreignkey')
    op.create_foreign_key('chars_table_group_id_fkey', 'chars_table', 'group', ['group_id'], ['id'])
    op.create_index('ix_chars_table_group_id', 'chars_table', ['group_id'], unique=False)
    op.drop_index(op.f('ix_chars_table_group_db_id'), table_name='chars_table')
    op.drop_column('chars_table', 'group_db_id')
    # ### end Alembic commands ###
