"""empty message

Revision ID: 92dd687058e4
Revises: eabdb9a82715
Create Date: 2019-02-28 14:52:34.443310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dd687058e4'
down_revision = 'eabdb9a82715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nick_name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['qq_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['qq_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('qq_user', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('qq_user', 'is_owner')
    op.drop_column('qq_user', 'user_name')
    op.drop_column('qq_user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qq_user', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    op.add_column('qq_user', sa.Column('user_name', sa.VARCHAR(), nullable=False))
    op.add_column('qq_user', sa.Column('is_owner', sa.BOOLEAN(), nullable=False))
    op.drop_column('qq_user', 'username')
    op.drop_table('group_members')
    # ### end Alembic commands ###
