"""empty message

Revision ID: e64efd84a332
Revises: 
Create Date: 2019-03-05 11:44:59.465902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64efd84a332'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('group_id', sa.String(length=20), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'group_id')
    )
    op.create_index(op.f('ix_group_group_id'), 'group', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_platform'), 'group', ['platform'], unique=False)
    op.create_table('main_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_user_email'), 'main_user', ['email'], unique=True)
    op.create_index(op.f('ix_main_user_username'), 'main_user', ['username'], unique=True)
    op.create_table('chars_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'version')
    )
    op.create_index(op.f('ix_chars_table_group_id'), 'chars_table', ['group_id'], unique=False)
    op.create_index(op.f('ix_chars_table_version'), 'chars_table', ['version'], unique=False)
    op.create_table('group_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('main_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_user_id'], ['main_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'user_id')
    )
    op.create_index(op.f('ix_group_user_main_user_id'), 'group_user', ['main_user_id'], unique=False)
    op.create_index(op.f('ix_group_user_platform'), 'group_user', ['platform'], unique=False)
    op.create_index(op.f('ix_group_user_user_id'), 'group_user', ['user_id'], unique=False)
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char', sa.String(length=6), nullable=False),
    sa.Column('codes', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=200), nullable=True),
    sa.Column('other_info', sa.String(length=200), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['chars_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'char')
    )
    op.create_index(op.f('ix_character_char'), 'character', ['char'], unique=False)
    op.create_index(op.f('ix_character_table_id'), 'character', ['table_id'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['group_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'user_id', 'group_id')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_platform'), 'group_members', ['platform'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_platform'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_character_table_id'), table_name='character')
    op.drop_index(op.f('ix_character_char'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_group_user_user_id'), table_name='group_user')
    op.drop_index(op.f('ix_group_user_platform'), table_name='group_user')
    op.drop_index(op.f('ix_group_user_main_user_id'), table_name='group_user')
    op.drop_table('group_user')
    op.drop_index(op.f('ix_chars_table_version'), table_name='chars_table')
    op.drop_index(op.f('ix_chars_table_group_id'), table_name='chars_table')
    op.drop_table('chars_table')
    op.drop_index(op.f('ix_main_user_username'), table_name='main_user')
    op.drop_index(op.f('ix_main_user_email'), table_name='main_user')
    op.drop_table('main_user')
    op.drop_index(op.f('ix_group_platform'), table_name='group')
    op.drop_index(op.f('ix_group_group_id'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
