"""empty message

Revision ID: e6c99a6c3071
Revises: be9e8ae40412
Create Date: 2019-06-08 16:47:19.849579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6c99a6c3071'
down_revision = 'be9e8ae40412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chai_wu_bi_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('main_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_user_id'], ['main_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chai_wu_bi_user_main_user_id'), 'chai_wu_bi_user', ['main_user_id'], unique=False)
    op.create_table('char_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('group_db_id', sa.Integer(), nullable=True),
    sa.Column('main_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_db_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['main_user_id'], ['main_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'version', name='c_chars_table')
    )
    op.create_index(op.f('ix_char_table_group_db_id'), 'char_table', ['group_db_id'], unique=False)
    op.create_index(op.f('ix_char_table_main_user_id'), 'char_table', ['main_user_id'], unique=False)
    op.create_index(op.f('ix_char_table_version'), 'char_table', ['version'], unique=False)
    op.create_table('word_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('group_db_id', sa.Integer(), nullable=True),
    sa.Column('main_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_db_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['main_user_id'], ['main_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='c_word_table')
    )
    op.create_index(op.f('ix_word_table_group_db_id'), 'word_table', ['group_db_id'], unique=False)
    op.create_index(op.f('ix_word_table_main_user_id'), 'word_table', ['main_user_id'], unique=False)
    op.create_index(op.f('ix_word_table_name'), 'word_table', ['name'], unique=True)
    op.create_index(op.f('ix_word_table_version'), 'word_table', ['version'], unique=False)
    op.drop_index('c_chars_table', table_name='chars_table')
    op.drop_index('ix_chars_table_group_db_id', table_name='chars_table')
    op.drop_index('ix_chars_table_version', table_name='chars_table')
    op.drop_index('name', table_name='chars_table')
    op.drop_table('chars_table')
    op.drop_index('c_words_table', table_name='words_table')
    op.drop_index('ix_words_table_group_db_id', table_name='words_table')
    op.drop_index('ix_words_table_name', table_name='words_table')
    op.drop_index('ix_words_table_version', table_name='words_table')
    op.drop_table('words_table')
    op.drop_constraint('article_ibfk_1', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'main_user', ['main_user_id'], ['id'])
    op.drop_constraint('character_ibfk_1', 'character', type_='foreignkey')
    op.create_foreign_key(None, 'character', 'char_table', ['table_db_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('comp_article', sa.Column('end_time', sa.Time(), nullable=False))
    op.add_column('comp_article', sa.Column('start_time', sa.Time(), nullable=False))
    op.alter_column('comp_article', 'group_db_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('comp_article_box', sa.Column('level', sa.Integer(), nullable=True))
    op.alter_column('comp_article_box', 'main_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('ix_comp_article_box_author', table_name='comp_article_box')
    op.drop_column('comp_article_box', 'author')
    op.drop_constraint('group_user_ibfk_1', 'group_user', type_='foreignkey')
    op.create_foreign_key(None, 'group_user', 'main_user', ['main_user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('word_ibfk_1', 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'word_table', ['table_db_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.create_foreign_key('word_ibfk_1', 'word', 'words_table', ['table_db_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'group_user', type_='foreignkey')
    op.create_foreign_key('group_user_ibfk_1', 'group_user', 'main_user', ['main_user_id'], ['id'])
    op.add_column('comp_article_box', sa.Column('author', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_comp_article_box_author', 'comp_article_box', ['author'], unique=False)
    op.alter_column('comp_article_box', 'main_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('comp_article_box', 'level')
    op.alter_column('comp_article', 'group_db_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('comp_article', 'start_time')
    op.drop_column('comp_article', 'end_time')
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.create_foreign_key('character_ibfk_1', 'character', 'chars_table', ['table_db_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key('article_ibfk_1', 'article', 'main_user', ['main_user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_table('words_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('group_db_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_db_id'], ['group.id'], name='words_table_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_words_table_version', 'words_table', ['version'], unique=False)
    op.create_index('ix_words_table_name', 'words_table', ['name'], unique=True)
    op.create_index('ix_words_table_group_db_id', 'words_table', ['group_db_id'], unique=False)
    op.create_index('c_words_table', 'words_table', ['name', 'version'], unique=True)
    op.create_table('chars_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('group_db_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_db_id'], ['group.id'], name='chars_table_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'chars_table', ['name'], unique=True)
    op.create_index('ix_chars_table_version', 'chars_table', ['version'], unique=False)
    op.create_index('ix_chars_table_group_db_id', 'chars_table', ['group_db_id'], unique=False)
    op.create_index('c_chars_table', 'chars_table', ['name', 'version'], unique=True)
    op.drop_index(op.f('ix_word_table_version'), table_name='word_table')
    op.drop_index(op.f('ix_word_table_name'), table_name='word_table')
    op.drop_index(op.f('ix_word_table_main_user_id'), table_name='word_table')
    op.drop_index(op.f('ix_word_table_group_db_id'), table_name='word_table')
    op.drop_table('word_table')
    op.drop_index(op.f('ix_char_table_version'), table_name='char_table')
    op.drop_index(op.f('ix_char_table_main_user_id'), table_name='char_table')
    op.drop_index(op.f('ix_char_table_group_db_id'), table_name='char_table')
    op.drop_table('char_table')
    op.drop_index(op.f('ix_chai_wu_bi_user_main_user_id'), table_name='chai_wu_bi_user')
    op.drop_table('chai_wu_bi_user')
    # ### end Alembic commands ###
