"""empty message

Revision ID: e8622f4e915b
Revises: 
Create Date: 2019-02-28 17:54:23.550737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8622f4e915b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char', sa.String(length=6), nullable=False),
    sa.Column('info', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_char'), 'character', ['char'], unique=False)
    op.create_index(op.f('ix_character_version'), 'character', ['version'], unique=False)
    op.create_table('qq_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=20), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qq_group_group_id'), 'qq_group', ['group_id'], unique=True)
    op.create_table('qq_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qq_user_user_id'), 'qq_user', ['user_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('nick_name', sa.String(length=50), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['qq_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['qq_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_members')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_qq_user_user_id'), table_name='qq_user')
    op.drop_table('qq_user')
    op.drop_index(op.f('ix_qq_group_group_id'), table_name='qq_group')
    op.drop_table('qq_group')
    op.drop_index(op.f('ix_character_version'), table_name='character')
    op.drop_index(op.f('ix_character_char'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
