"""character

Revision ID: eabdb9a82715
Revises: 9c80538546bd
Create Date: 2019-02-21 17:46:52.105798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabdb9a82715'
down_revision = '9c80538546bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_char'), 'character', ['char'], unique=False)
    op.create_index(op.f('ix_character_version'), 'character', ['version'], unique=False)
    op.create_table('qq_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qq_group_group_id'), 'qq_group', ['group_id'], unique=True)
    op.create_table('qq_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qq_user_user_id'), 'qq_user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qq_user_user_id'), table_name='qq_user')
    op.drop_table('qq_user')
    op.drop_index(op.f('ix_qq_group_group_id'), table_name='qq_group')
    op.drop_table('qq_group')
    op.drop_index(op.f('ix_character_version'), table_name='character')
    op.drop_index(op.f('ix_character_char'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
