"""empty message

Revision ID: f7b97400a6d9
Revises: 0253176ac39b
Create Date: 2019-03-06 23:46:22.673773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b97400a6d9'
down_revision = '0253176ac39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'codes',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('main_user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('main_user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('main_user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('main_user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('character', 'codes',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
