"""empty message

Revision ID: fb10da98f200
Revises: e64efd84a332
Create Date: 2019-03-06 16:26:27.212910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb10da98f200'
down_revision = 'e64efd84a332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_user_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('group_db_id', sa.Integer(), nullable=False),
    sa.Column('user_db_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_db_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_db_id'], ['group_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'user_db_id', 'group_db_id')
    )
    op.create_index(op.f('ix_group_user_relation_group_db_id'), 'group_user_relation', ['group_db_id'], unique=False)
    op.create_index(op.f('ix_group_user_relation_platform'), 'group_user_relation', ['platform'], unique=False)
    op.create_index(op.f('ix_group_user_relation_user_db_id'), 'group_user_relation', ['user_db_id'], unique=False)
    op.drop_index('ix_group_members_group_id', table_name='group_members')
    op.drop_index('ix_group_members_platform', table_name='group_members')
    op.drop_index('ix_group_members_user_id', table_name='group_members')
    op.drop_table('group_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_owner', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='group_members_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['group_user.id'], name='group_members_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='group_members_pkey'),
    sa.UniqueConstraint('platform', 'user_id', 'group_id', name='group_members_platform_user_id_group_id_key')
    )
    op.create_index('ix_group_members_user_id', 'group_members', ['user_id'], unique=False)
    op.create_index('ix_group_members_platform', 'group_members', ['platform'], unique=False)
    op.create_index('ix_group_members_group_id', 'group_members', ['group_id'], unique=False)
    op.drop_index(op.f('ix_group_user_relation_user_db_id'), table_name='group_user_relation')
    op.drop_index(op.f('ix_group_user_relation_platform'), table_name='group_user_relation')
    op.drop_index(op.f('ix_group_user_relation_group_db_id'), table_name='group_user_relation')
    op.drop_table('group_user_relation')
    # ### end Alembic commands ###
